# Common variables: IP ranges, DNS servers, gateway IPs, subnet masks
ip_address: "192.168.100.10"
netmask: "255.255.255.0"
gateway: "192.168.100.1"
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
vpn_server_ip: "192.168.200.1"
firewall_rules:
  - port: 22
    proto: tcp
    action: accept
  - port: 80
    proto: tcp
    action: accept
